version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=delete
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5g
#    ports:
#      - "5433:5432"
    expose:
      - "5432"