version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
      - ./bot_session:/app/bot_session
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=delete
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5g
    ports:
      - "5433:5432"